spring:
  application:
    name: VCarBE
  data:
    redis:
      host: redis-14434.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14434
      password: QSXXcWgl2sserlbefUsJlestoMv5fuF9
    mongodb:
      uri: mongodb+srv://mongobasic:Social123456789Media@cluster0.oiyfqvw.mongodb.net/VCar?retryWrites=true&w=majority&appName=Cluster0
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 32927445083-prq50j015hn7k7k7tmjpljmttfaftn43.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://localhost:3000,http://127.0.0.1:5500,http://localhost:5173
    oauth2:
      authorizedRedirectUris: http://localhost:3000/oauth2/redirect,https://localhost:3000/oauth2/redirect,http://localhost:5173/oauth2/redirect

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME:laminhtam5523@gmail.com}
  password: ${MAIL_PASSWORD:zwyk itwy csoe opwd}
  sender: ${MAIL_SENDER:VCar}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true